name: Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy my app
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: production
          initial-status: success