name: Update Change PR

on:
  push:
    branches:
      - 'gerrit-change/[0-9]+/[0-9]+'
      - '!gerrit-change/[0-9]+/1'
      # Merge branches
      # - gerrit-change/[0-9]+/[0-9]+
jobs:
  update_pr_on_subsequent_gerrit_change:
    name: Update PR from Patch on Gerrit Change
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Deep fetch
        fetch-depth: 0
    - name: Update Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      run: |
        # Close the PR for the previous branch
        gh pr close $(dirname ${{ github.ref_name }})/`expr $(basename ${{ github.ref_name }}) - 1`

        # Open a new PR for the current branch
        gh pr create --fill-verbose